# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .purrl import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "purrl",
  "mod": "index",
  "fqn": "pulumiverse_purrl",
  "classes": {
   "purrl:index:Purrl": "Purrl"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "purrl",
  "token": "pulumi:providers:purrl",
  "fqn": "pulumiverse_purrl",
  "class": "Provider"
 }
]
"""
)
