# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_pucurl.pucurl as __pucurl
    pucurl = __pucurl
else:
    pucurl = _utilities.lazy_import('pulumi_pucurl.pucurl')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "pucurl",
  "mod": "pucurl",
  "fqn": "pulumi_pucurl.pucurl",
  "classes": {
   "pucurl:pucurl:PuCurl": "PuCurl"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "pucurl",
  "token": "pulumi:providers:pucurl",
  "fqn": "pulumi_pucurl",
  "class": "Provider"
 }
]
"""
)
