// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { PurrlArgs } from "./purrl";
export type Purrl = import("./purrl").Purrl;
export const Purrl: typeof import("./purrl").Purrl = null as any;
utilities.lazyLoad(exports, ["Purrl"], () => require("./purrl"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "purrl:purrl:Purrl":
                return new Purrl(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("purrl", "purrl", _module)
