// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { PuCurlArgs } from "./puCurl";
export type PuCurl = import("./puCurl").PuCurl;
export const PuCurl: typeof import("./puCurl").PuCurl = null as any;
utilities.lazyLoad(exports, ["PuCurl"], () => require("./puCurl"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "pucurl:pucurl:PuCurl":
                return new PuCurl(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("pucurl", "pucurl", _module)
